version: "3"

services:
  django-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  test:
    build: .
    command: python3 manage.py test

networks:
  mynetwork: