# Generated by Django 4.1.7 on 2023-04-01 15:21

import EcoQuest.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomos',
            fields=[
                ('NomosId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perifereia',
            fields=[
                ('PerifereiaId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('PointOfInterestId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoQuest.category')),
                ('NomosId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EcoQuest.nomos')),
                ('PerifereiaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EcoQuest.perifereia')),
            ],
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('SavedSearchId', models.BigAutoField(primary_key=True, serialize=False)),
                ('CenterLatitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('CenterLongitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('Radius', models.DecimalField(decimal_places=6, max_digits=9)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoQuest.category')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoiPicture',
            fields=[
                ('PoiPictureId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to=EcoQuest.models.upload_to)),
                ('PointOfInterestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoQuest.pointofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Text', models.CharField(max_length=1000)),
                ('Read', models.BooleanField(default=False)),
                ('Retrieved', models.BooleanField(default=False)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('PointOfInterestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoQuest.pointofinterest')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
