# Generated by Django 4.1.7 on 2023-03-30 19:46

import EcoQuest.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EcoQuest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomos',
            fields=[
                ('NomosId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perifereia',
            fields=[
                ('PerifereiaId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pointofinterest',
            old_name='Category',
            new_name='CategoryId',
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('SavedSearchId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Radius', models.FloatField()),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoQuest.category')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoiPicture',
            fields=[
                ('PoiPictureId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to=EcoQuest.models.upload_to)),
                ('PointOfInterestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoQuest.pointofinterest')),
            ],
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='NomosId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EcoQuest.nomos'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='PerifereiaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EcoQuest.perifereia'),
        ),
    ]
