# Generated by Django 4.1.5 on 2023-07-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoQuest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterest',
            name='CategoryId',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='CategoryId',
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='Categories',
            field=models.ManyToManyField(to='EcoQuest.category'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='KeyWords',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='Categories',
            field=models.ManyToManyField(to='EcoQuest.category'),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='CenterLatitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='CenterLongitude',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='Radius',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
