# Generated by Django 4.1.5 on 2023-07-09 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EcoQuest', '0002_remove_pointofinterest_categoryid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePois',
            fields=[
                ('FavoriteId', models.BigAutoField(primary_key=True, serialize=False)),
                ('PointOfInterestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoQuest.pointofinterest')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
