# Generated by Django 4.1.5 on 2023-07-09 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EcoQuest', '0003_favoritepois'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='IsFavoriteTo',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FavoritePois',
        ),
    ]
