# Generated by Django 4.1.5 on 2023-07-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoQuest', '0005_alter_pointofinterest_isfavoriteto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='Description',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
